//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "servers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub rules_channel: i64,
    pub screening_channel: i64,
    pub questioning_role: i64,
    pub questioning_category: i64,
    pub mod_role: i64,
    pub mod_channel: i64,
    pub member_role: i64,
    pub main_channel: i64,
    pub blocked_images: Option<Vec<u8>>,
    pub triggers: Option<Vec<u8>>,
    pub entry_modal: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
